from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("404/", views.comming_soon, name="404"),
    path('forbidden/', views.forbidden_page, name='forbidden'),

    path("login/", views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
    #region Administrator
    path('builder2/', views.builder2, name='builder2'),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("courses/", views.courses, name="courses"),
    path("organization/", views.org_chart, name="organization"),
    path("oorganization/chart/", views.org_chart2, name="org"),
    path("database-settings/", views.database_settings, name="database-settings"),
    path("adminpage/", views.admin, name="adminpage"),
    path("api/create-admin/", views.create_admin, name="create_admin"),
    path("api/admin-users/", views.admin_users, name="admin-users"),
    path("api/admin-update/<int:pk>/", views.update_admin, name="admin-update"),
    path("api/admin-delete/<int:pk>/", views.delete_admin),
    path("news/", views.news, name="news"),
    path("instructor/", views.instructor, name="instructor"),
    path("instructor-new/", views.instructornew, name="instructornew"),
    path("student-new/", views.studentnew, name="studentnew"),
    path("", views.sidebar, name="sidebar"),
    path("", views.navbar, name="navbar"),
    path("search/", views.global_search, name="global-search"),
    path("search-instructor/", views.global_search_instructor_only, name="global-search-instructor-only"),
    path('profile-viewer/', views.profileviewer, name='profile-viewer'),
    path("instructor-attendance/", views.instructorattendance, name="instructor-attendance"),
    path('instructor-dtr/', views.instructordtr, name='instructor-dtr'),
    path('instructor/<int:id>/', views.instructorprofile, name='instructor-profile'),
    path('student/<int:id>/', views.studentprofile, name='student-profile'),
    path('comlab/', views.comlab, name='comlab'),
    path('add-comlab/', views.add_comlab, name='add_comlab'),
    path('equipment-list/', views.get_equipment_list, name='equipment_list'),
    path('save-equipment/', views.save_equipment_borrow, name='save_equipment'),
    path('mark-returned/<int:id>/', views.mark_returned, name='mark_returned'),
    path('add-report/', views.add_report, name='add_report'),
    path('get-reports/', views.get_reports, name='get_reports'),
    path('delete-report/<int:report_id>/', views.delete_report, name='delete_report'),    
    path('edit-report/<int:report_id>/', views.edit_report, name='edit_report'),
    path("feed/", views.post_feed, name="post_feed"),
    path('posts/new/', views.new_posts, name='new_posts'),
    path('create_post/', views.create_post, name='create_post'),
    path("like/<int:post_id>/", views.toggle_like, name="toggle_like"),
    path("add-comment/<int:post_id>/", views.add_comment),
    path("delete-post/<int:post_id>/", views.delete_post),
    path("posts/", views.post_list, name='post_list'),
    path("new_posts/", views.new_posts, name='new_posts'),
    path("add-instructor/", views.add_instructor, name="add_instructor"),
    path('api/instructor/<int:id>/update/', views.update_instructor, name='update_instructor'),
    path("add-student/", views.add_student, name="add_student"),
    path("classroom/", views.classroom, name="classroom"),
    path("classrooms/", views.classroom_dashboard, name="classroom_dashboard"),
    path("classrooms/update/<int:pk>/", views.classroom_update_ajax),
    path("classrooms/delete/<int:pk>/", views.classroom_delete_ajax),
    path("classrooms/create/", views.classroom_create_ajax, name="classroom_create_ajax"),
    path("api/classrooms/", views.classroom_list),
    path("api/instructors/", views.class_Instructor_list),
    path("api/instructors-edit/", views.class_Instructor_list_edit),
    path("subject/", views.subject, name="subject"),
    path("subject/create/", views.subject_create_ajax, name="subject_create_ajax"),
    path("api/subjects/", views.subject_list),
    path("subject/update/<int:pk>/", views.subject_update_ajax),
    path("subject/delete/<int:pk>/", views.subject_delete_ajax),
    path("schedule/add/", views.add_schedule, name="add_schedule"),
    path("schedule/delete/", views.delete_schedule, name="del_schedule"),
    path("api/subjects-req/", views.subject_scheduling_api, name="subject_api"),
    path("api/classroom-req/", views.classroom_scheduling_api, name="classroom_api"),
    path("api/schedules/", views.schedule_list),
    path('api/class-schedules/<int:pk>/', views.class_schedule_list, name='class_schedule_list'),
    path('users/preview/', views.preview_users, name='preview_users'),
    path('users/preview-student/', views.preview_users_student, name='preview_users_student'),
    path('users/bulk-upload/', views.bulk_upload_users_ajax, name='bulk_upload_users_ajax'),
    path('instructors/table/', views.instructor_table),
    path('update-profile-photo/<int:pk>/', views.update_profile_photo, name='update_profile_photo'),
    path('update-profile/<int:pk>/', views.update_profile, name='update_profile'),
    path("course/create/", views.course_create_ajax, name="course_create_ajax"),
    path("api/course/", views.course_list),
    path("course/update/<int:pk>/", views.course_update_ajax),
    path("course/delete/<int:pk>/", views.course_delete_ajax),

    path("instructor/schedule/get/", views.instructor_get_schedule_per_id),
    path("instructor/schedule/update/", views.instructor_update_schedule_per_id),


    path('api/fingerprint/enroll/', views.enroll_fingerprint, name='enroll_fingerprint'),
    path('api/fingerprint/verify/', views.verify_fingerprint, name='verify_fingerprint'),
    path('api/fingerprint/', views.fingerprint_command, name='fingerprint_command'),
    path("api/fingerprint/commands/", views.fingerprint_commands, name="fingerprint_commands"),

    path("api/fingerprint/start-verify/", views.start_verify, name="start_verify"),
    path("api/fingerprint/start-enroll/", views.start_enroll, name="start_enroll"),
    path('api/fingerprint/commands/<int:cmd_id>/', views.fingerprint_command_detail, name='fingerprint_command_detail'),

    path('api/fingerprint/set/logs/', views.set_fingerprint_logs),
    path('api/fingerprint/get/logs/', views.get_fingerprint_logs),
    path('api/fingerprint/get/logs/update/<int:pk>/', views.get_fingerprint_logs_update),

    path('api/fingerprint/status/', views.fingerprint_status),
    path("api/update-profile-fingerprint/", views.save_fingerprint, name="save_fingerprint"),
    path('instructor-profile-fp/<int:id>/', views.getprofilebyfp, name='instructor-profile-fp'),

    path("instructor/password/reset/", views.instructor_password_reset, name="instructor_password_reset"),
    path("instructor/account/disable/", views.instructor_account_disable, name="instructor_account_disable"),
    path("instructor/account/enable/", views.instructor_account_enable, name="instructor_account_enable"),
    #endregion

    #region USERS
    path('instructor/dashboard/', views.dashboard_ins, name='dashboard_ins'),
    path('instructor/news/', views.news_ins, name='news_ins'),
    path("instructor/schedule/", views.schedule_ins, name="schedule_ins"),
    path('instructor/dtr/', views.dtr_ins, name='dtr_ins'),
    path('instructor/profile/', views.profile_ins, name='profile_ins'),
    path('instructor/api/update-profile/', views.update_my_profile, name='update_my_profile'),
    path('instructor/api/update-profile/password/', views.change_my_password, name='change_my_password'),
    path('instructor/api/update-profile/reset-password/', views.send_password_reset_email, name='send_password_reset_email'),
    path('instructor/view/<int:id>/', views.view_profile, name='view-profile'),
    #endregion

    path("student/", views.student, name="student"),

    #region STUDENT
    path('student/dashboard/', views.dashboard_student, name='dashboard_student'),
    path('student/news/', views.news_student, name='news_student'),
    path("student/schedule/", views.schedule_student, name="schedule_student"),
    path('student/dtr/', views.dtr_student, name='dtr_student'),
    path('student/profile/', views.profile_student, name='profile_student'),
    path('student/api/update-profile/', views.update_my_profile_student, name='update_my_profile_student'),
    path('student/api/update-profile/password/', views.change_my_password_student, name='change_my_password_student'),
    path('student/api/update-profile/reset-password/', views.send_password_reset_email_student, name='send_password_reset_email_student'),
    #endregion
]