# Generated by Django 6.0.3 on 2026-04-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectcourse', to='main.course'),
        ),
    ]
