# Generated by Django 6.0.3 on 2026-04-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subjects_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_masteradmin',
            field=models.BooleanField(default=True),
        ),
    ]
